# Generated by Django 4.1.4 on 2022-12-20 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 15, 25)),
        ),
    ]
