# Generated by Django 4.1.4 on 2022-12-21 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_votes_vote_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 7, 47)),
        ),
    ]
